services:
  - type: worker
    name: agent/life-automation-agent
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "agent/python run_agent.py"
    autoDeploy: true
